### ISSUE TITLE
内置规则引擎推送数据到RocketMQ

### ISSUE THREAD

**Issue by JiaDeng-Git** [apache/bifromq#44]
大佬，能否支持内置规则引擎推送数据到RocketMQ。
![image](https://github.com/baidu/bifromq/assets/44760427/a2796e45-d779-483b-823c-655147b81e39)

**Comment by popduke** [comment]
BifroMQ不会内置"规则引擎"，[这里](https://bifromq.io/zh-Hans/docs/2.0.0/faq/bifromq/)有说明：
但支持以更解耦方式的实现[数据集成](https://bifromq.io/zh-Hans/docs/2.0.0/user_guide/integration/integration/)，
可以参考BifroMQ桥接kafka的实现：https://github.com/Gujiawei-Edinburgh/Data-Integration
